// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitTradingQueen() (*TradingQueen, func(), error) {
	dburi := provideDBURI()
	mongoDB, cleanup, err := provideMongoDB(dburi)
	if err != nil {
		return nil, nil, err
	}
	manager := provideSimulationManager(mongoDB)
	luaScriptHandler := provideLuaScriptHandler(manager)
	strategyManager := provideStrategyManager(mongoDB, luaScriptHandler)
	userManager := provideUserManager(mongoDB)
	exchangeManager := provideExchangeManager(userManager)
	platform := providePlatform(strategyManager, exchangeManager, userManager)
	router := provideRouter(mongoDB, platform, strategyManager, exchangeManager, userManager, manager)
	tradingQueen := NewTradingQueen(router)
	return tradingQueen, func() {
		cleanup()
	}, nil
}
